config/routes.rb
Busapp::Application.routes.draw do
  root 'routes#index'

  get '/routes/:id/selection', to: 'routes#selection', as: :route_selection
  post '/routes/:id/selection', to: 'routes#create_user_route', as: :create_user_route
  get '/routes/:id/directions', to: 'routes#directions', as: :route_directions

  get '/userroutes/start_tour', to: 'user_routes#start_tour_info'
  get '/map', to: 'routes#map'
  get '/tour', to: 'route_sequences#tour', as: :tour

  resources :route_sequences, only: [:index, :show]

  get 'landmarks', to: 'audio_clips#index'
  get '/audio_clips', to: 'audio_clips#route_index'
  get '/set_current_clip', to: 'user_routes#set_current_clip'

  resources :routes

  devise_for :users, :controllers => {:registrations => 'users', omniauth_callbacks: "omniauth_callbacks"}
  
  devise_scope :user do
    resources :users, only: [] do
      collection do
        get :location, to: "users#set_location"
      end
    end
  end

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :audio_clips
  has_many :user_routes
  has_many :route_sequences
  has_many :stops, through: :route_sequences
  has_many :users, through: :user_routes
  
  WEST_EAST_START1 = ["11", "14", "RV1", "139"]
  EAST_WEST_START1 = ["15", "9", "274"]

  def east_or_west(route_name, direction)
    if (Route::WEST_EAST_START1.include? route_name) && (direction == 1)
      :east_sequence
    elsif (Route::WEST_EAST_START1.include? route_name) && (direction == 2)
      :west_sequence
    elsif (Route::EAST_WEST_START1.include? route_name) && (direction == 1)
      :west_sequence
    elsif (Route::EAST_WEST_START1.include? route_name) && (direction == 2)
      :east_sequence
    else
      puts "ERROR"
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /routes/1/selection
  def selection
    @route = Route.find(params[:id])
    @user_route = @route.user_routes.build
  end

  def map
  end

  # POST /routes/1/selection
  def create_user_route
    @route = Route.find(params[:id])

    case params[:start_stop].to_i
    when 0
      direction = params[:direction]
      tour_stops = @route.route_sequences.where(direction: direction)
      closest_stop_id = tour_stops.near([current_user.latitude, current_user.longitude], 1000).first.stop_id
      start_stop = closest_stop_id
    when -1
    # To be filled in with West Terminus
      start_stop = -1
    when 1
    # To be filled in with East Terminus
      start_stop = 1
    end

    @route.user_routes.build(
      user_id: current_user.id,
      direction: params[:direction].to_i,
      current: true, 
      start_stop_id: start_stop
      )
    @route.save

    redirect_to route_directions_path(@route)
  end

  def directions

  end
  
  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render action: 'show', status: :created, location: @route }
      else
        format.html { render action: 'new' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper

  def direction_value1(route)
    if Route::EAST_WEST_START1.include? route.name
      1
    else
      2
    end
  end

  def direction_value2(route)
    if direction_value1(route) == 1
      2
    else
      1
    end
  end

end

app/views/routes/_form.html.haml
= form_for @route do |f|
  - if @route.errors.any?
    #error_explanation
      %h2= "#{pluralize(@route.errors.count, "error")} prohibited this route from being saved:"
      %ul
        - @route.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/routes/directions.html.haml
%h1 Go to the desired bus stop

%div#bus-stop-map-canvas

%div#legend
  %b Legend
  %br
  %img{src: "/assets/bus-stop.png"} 
  Bus stop
  %br
  #circle
  Your location

#upcoming-buses

= button_to "Start tour", tour_path, :class => "btn btn-default", :method => :get 
 

app/views/routes/edit.html.haml
%h1 Editing route

= render 'form'

= link_to 'Show', @route
\|
= link_to 'Back', routes_path

app/views/routes/index.html.haml
%h1 Choose a route

.jumbotron
  %h2 placeholder: map

/ - @routes.each do |route|
/   .row
/     %button.btn.btn-info
/       Route '
/       =route.name
/       ': 
/       =route.description 

- @routes.each do |route|
  = link_to("Route #{route.name}: #{route.description}", route_selection_path(route), class: 'btn btn-info route-selection')
  %br

app/views/routes/map.html.haml
%div#map-canvas

app/views/routes/new.html.haml
%h1 New route

= render 'form'

= link_to 'Back', routes_path

app/views/routes/selection.html.haml
%h1
  Route 
  = @route.name

%h2 Main landmarks

%ul
  - @route.audio_clips.where(main_attraction: true).each do |landmark|
    %li
      = landmark.name

%h2 Start your tour

= form_tag(create_user_route_path(@route), method: "post") do
  .form-group
    = label_tag(:start_stop, "Start from")
    = select_tag(:start_stop, options_for_select([["Stop closest to me", 0],["Tour start (West): #{@route.start_stop}", -1],["Tour start (East): #{@route.end_stop}", 1]]), :class => "form-control")

  .form-group
    = label_tag(:direction, "Going towards")
    = select_tag(:direction, options_for_select([["#{@route.start_stop}", direction_value1(@route)],["#{@route.end_stop}", direction_value2(@route)]]), :class => "form-control")

  = hidden_field_tag(:user_id, current_user.id)

  = submit_tag("Go", :class => "btn btn-default")

/ = form_for @user_route do |f|
/   .form-group
/     = f.label
/     = f.select

/   .form-group
/     = f.label
/     = f.select

/   = f.submit

/ options_for_select([["Stop closest to me", 0],["Tour start: #{@route.start_stop}", -1],["Tour start: #{@route.end_stop}", 1]])

app/views/routes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @route.name

= link_to 'Edit', edit_route_path(@route)
\|
= link_to 'Back', routes_path